name: Build Zebra

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Theos Dependencies
      run: brew install ldid fakeroot make

    - name: Install Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: gmake package

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20

